from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(name="Asset", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("symbol", models.CharField(max_length=50, unique=True)), ("name", models.CharField(max_length=200)), ("asset_type", models.CharField(choices=[("stock","Stock"),("crypto","Crypto"),("fx","FX"),("commodity","Commodity"),("fund","Fund")], default="stock", max_length=30)), ("currency", models.CharField(default="USD", max_length=10)), ("active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="EconomicAuditLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(max_length=100)), ("detail", models.TextField(blank=True)), ("approved", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="EconomicReport", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=250)), ("report_type", models.CharField(default="market", max_length=50)), ("summary", models.TextField()), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Portfolio", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200, unique=True)), ("base_currency", models.CharField(default="USD", max_length=10)), ("paper_trading", models.BooleanField(default=True)), ("cash_balance", models.DecimalField(decimal_places=4, default=0, max_digits=24)), ("active", models.BooleanField(default=True))]),
        migrations.CreateModel(name="RiskPolicy", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200, unique=True)), ("max_order_value", models.DecimalField(decimal_places=4, default=0, max_digits=24)), ("max_daily_loss", models.DecimalField(decimal_places=4, default=0, max_digits=24)), ("require_owner_approval", models.BooleanField(default=True)), ("enabled", models.BooleanField(default=True))]),
        migrations.CreateModel(name="Strategy", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200, unique=True)), ("description", models.TextField(blank=True)), ("enabled", models.BooleanField(default=False)), ("paper_only", models.BooleanField(default=True))]),
        migrations.CreateModel(name="MarketDataSnapshot", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("timestamp", models.DateTimeField(auto_now_add=True)), ("price", models.DecimalField(decimal_places=10, max_digits=24)), ("volume", models.DecimalField(decimal_places=10, default=0, max_digits=30)), ("source", models.CharField(default="manual", max_length=100)), ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="economy.asset"))]),
        migrations.CreateModel(name="Position", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity", models.DecimalField(decimal_places=10, default=0, max_digits=30)), ("average_price", models.DecimalField(decimal_places=10, default=0, max_digits=24)), ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="economy.asset")), ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="positions", to="economy.portfolio"))]),
        migrations.CreateModel(name="OrderIntent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("side", models.CharField(choices=[("buy","Buy"),("sell","Sell")], max_length=10)), ("quantity", models.DecimalField(decimal_places=10, max_digits=30)), ("limit_price", models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)), ("status", models.CharField(choices=[("pending","Pending approval"),("approved","Approved"),("rejected","Rejected"),("paper_executed","Paper executed"),("blocked","Blocked")], default="pending", max_length=20)), ("owner_approved", models.BooleanField(default=False)), ("real_execution_requested", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("approved_at", models.DateTimeField(blank=True, null=True)), ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="economy.asset")), ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="economy.portfolio")), ("strategy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="economy.strategy"))]),
        migrations.CreateModel(name="Trade", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("executed_price", models.DecimalField(decimal_places=10, max_digits=24)), ("executed_quantity", models.DecimalField(decimal_places=10, max_digits=30)), ("fee", models.DecimalField(decimal_places=10, default=0, max_digits=24)), ("paper", models.BooleanField(default=True)), ("executed_at", models.DateTimeField(auto_now_add=True)), ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="trade", to="economy.orderintent"))]),
        migrations.AlterUniqueTogether(name="position", unique_together={("portfolio","asset")}),
    ]
