from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("economy", "0001_initial")]
    operations = [
        migrations.CreateModel(name="SignalProduct", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200, unique=True)), ("description", models.TextField()), ("price", models.DecimalField(decimal_places=4, max_digits=24)), ("currency", models.CharField(default="IRR", max_length=10)), ("active", models.BooleanField(default=True)), ("disclaimer", models.TextField(default="Signals are informational and do not guarantee profit.")), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="SignalPurchase", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("amount", models.DecimalField(decimal_places=4, max_digits=24)), ("currency", models.CharField(default="IRR", max_length=10)), ("status", models.CharField(choices=[("pending","Pending"),("paid","Paid"),("failed","Failed"),("refunded","Refunded")], default="pending", max_length=20)), ("gateway", models.CharField(default="sandbox", max_length=50)), ("authority", models.CharField(blank=True, max_length=200)), ("paid_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="economy.signalproduct")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="signal_purchases", to="auth.user"))]),
        migrations.CreateModel(name="Signal", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("side", models.CharField(choices=[("buy","Buy"),("sell","Sell"),("hold","Hold")], max_length=10)), ("entry_price", models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)), ("stop_loss", models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)), ("take_profit", models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)), ("rationale", models.TextField(blank=True)), ("published", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="economy.asset")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="signals", to="economy.signalproduct"))]),
    ]
