from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [("office", "0002_erp_modules")]
    operations = [
        migrations.CreateModel(name="WorkflowApproval", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=250)),("status",models.CharField(choices=[("pending","در انتظار"),("approved","تأیید"),("rejected","رد")],default="pending",max_length=20)),("payload",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("decided_at",models.DateTimeField(blank=True,null=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="workflow_approvals",to="office.company")),("requested_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="workflow_requests",to=settings.AUTH_USER_MODEL)),("approver",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="workflow_approvals",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="PayrollRecord", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("period",models.CharField(max_length=20)),("gross",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("deductions",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("net",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("status",models.CharField(choices=[("draft","پیش‌نویس"),("approved","تأیید"),("paid","پرداخت")],default="draft",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("employee",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="payroll_records",to="office.employee"))]),
        migrations.CreateModel(name="PurchaseOrder", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("supplier",models.CharField(max_length=200)),("number",models.CharField(max_length=80)),("total",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("status",models.CharField(choices=[("draft","پیش‌نویس"),("approved","تأیید"),("received","دریافت"),("cancelled","لغو")],default="draft",max_length=20)),("order_date",models.DateField()),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="purchase_orders",to="office.company"))]),
        migrations.CreateModel(name="SalesOrder", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("customer",models.CharField(max_length=200)),("number",models.CharField(max_length=80)),("total",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("status",models.CharField(choices=[("draft","پیش‌نویس"),("confirmed","تأیید"),("delivered","تحویل"),("cancelled","لغو")],default="draft",max_length=20)),("order_date",models.DateField()),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="sales_orders",to="office.company"))]),
    ]
